#!/bin/sh
# Export $PATH so the script can find the binaries
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/

# Set the required variables
client=""
token=""

# Don’t install if netclient doesn’t exist
netclient=/usr/local/bin/netclient
if [ ! -f "$netclient" ]; 
 then 
	echo "netclient not found. Please install it first."
  exit 1
else

# Find machine Serial number (Mosyle variables)
echo Serial %SerialNumber% 
# Next find machine device name (Mosyle variables)
echo Name %DeviceName% 
# Let's see if it worked
echo joining Netmaker network for %SerialNumber% %DeviceName%
cd /usr/local/
sudo netclient join --name "%SerialNumber%"" ""%DeviceName%" -t $token
echo joined "%SerialNumber%"" ""%DeviceName%" to $client network

fi
exit 0
